---
- hosts: all

  tasks:
    - name: Check OS version
      shell: cat /etc/os-release
      register: out

    - debug:
        msg: "{{ out.stdout_lines }}"
    - debug:
        msg: "{{ out.stderr_lines }}"  
