---
- hosts: all

  tasks:
    - name: Check OS version
      shell: cat /etc/os-release
      register: out

    - debug: msg="{{ out.stdout | to_nice_json }}"
    - debug: msg="{{ out.stderr | to_nice_json }}"  
